---
version: 0.2

env:
  DOCKER_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"    
  pre_build:
    commands:
      - echo "Logging into ECR"
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - export START_TIME=$( date +%s )
      - echo STARTING TIME = $START_TIME
      - echo "Parsing Version and Name from pom.xml"
      - export PROJECT_VERSION=$(xmlstarlet sel -t -v /_:project/_:version pom.xml)
      - export PROJECT_NAME=$(xmlstarlet sel -t -v /_:project/_:artifactId pom.xml)
      - export DOKCER_TAG=$DOCKER_REGISTRY/$PROJECT_NAME:$PROJECT_VERSION
  build:
    commands:
      - echo "==========Debug info=========="
      - printenv
      - echo "==========Enf of Debug info=========="
      - echo "Building docker image"
      - docker build -f docker/Dockerfile.build -t $DOCKER_TAG .
  post_build:
    commands:
      - echo "Build completed in $(( $( date +%s ) - START_TIME ))s"
      - echo "Pushing docker image into ECR"
      - docker push $DOCKER_TAG
