node {
    def mvnHome
    def pom
    def github = [
            'credentialsId': '8a330b0a-a7dc-47aa-862a-72ac90cfe0d7',
            'url': 'https://github.com/Roman-Dudar/spring-petclinic',
            'branch': 'master'
    ]

    def CF_CREDID = '2d1e3235-6a3c-4faf-9773-3a7876ab70e4'

    stage('Checkout') {
        git url: github.url, credentialsId: github.credentialsId, branch: github.branch
        mvnHome = tool 'M3'

        pom = readMavenPom file: 'pom.xml'
    }

    stage('Build') {
        // Run the maven build
        if (isUnix()) {
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
        } else {
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
        }

        echo "!target/${pom.artifactId}-${pom.version}.jar > .cfignore"
    }

    stage('Deploy to pcf') {
        cfPush(
                target:         'api.run.pivotal.io',
                organization:   'roman-dudar',
                cloudSpace:     'development',
                credentialsId:  CF_CREDID,
                selfSigned: true,
                manifestChoice: [
                        value: 'jenkinsConfig',
                        appName: 'petclinic-demo',
                        memory: 1024,
                        instances: 1,
                        path: "target/${pom.artifactId}-${pom.version}.jar",
                        buildpack: 'https://github.com/cloudfoundry/java-buildpack.git#v4.5'
                ]
        )
    }

    stage('Results') {
        archive "target/${pom.artifactId}-${pom.version}.jar"
    }

}
